version: '3.3'
services:

    frontend:
        image: afsanarozan/cafe-frontend:dev
        container_name: frontend
        ports:
            - 8080:80
        networks: 
            - deploy
        environment:
            - VUE_APP_URL=http://18.206.186.76:9191
        

networks:
    deploy:
        driver: bridge