version: '3.3'
services:

    frontend:
        image: afsanarozan/cafe-frontend:prod
        container_name: frontend
        ports:
            - 8080:80
        networks: 
            - deploy
        environment:
            - VUE_APP_URL=http://3.92.223.179     

networks:
    deploy:
        driver: bridge