version: '3.3'
services:

    frontend:
        image: afsanarozan/cafe-frontend:dev
        container_name: frontend
        networks: 
            - deploy
        environment:
            - VUE_APP_URL=http://3.92.223.179:9191
        

networks:
    deploy:
        driver: bridge